---
compose_url: https://github.com/docker/compose/releases/download/1.21.0/docker-compose
compose_completition_url: https://raw.githubusercontent.com/docker/compose/1.21.0/contrib/completion/bash/docker-compose