---
- name: add Repo
  apt_repository: 
    repo: "{{ remmina_repo }}"
    update_cache: yes 
  become: true

- name: install package
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes
    force: yes
  with_items:
    - remmina
    - remmina-plugin-rdp 
    - remmina-plugin-secret
  become: true