---
- name: Check if vagrant is installed
  command: dpkg-query -W vagrant
  register: vagrant_check_deb
  failed_when: vagrant_check_deb.rc > 1
  changed_when: vagrant_check_deb.rc == 1

- name: Download vagrant
  get_url: 
    url: "{{ vagrant_url }}"
    dest: "/tmp/{{ vagrant_version }}.deb"
  when: vagrant_check_deb.rc == 1
  become: true

- name: Install vagrant
  apt: 
    deb: "/tmp/{{ vagrant_version }}.deb"
  when: vagrant_check_deb.rc == 1
  become: true

- name: Update and Upgrade apt cache
  apt: 
    update_cache: yes 
    upgrade: yes
  become: true