---
- name: install key
  apt_key:
    url: "{{ vscode_ulrkey }}"
    state: present
  become: yes

- name: install VS Code repo
  apt_repository:
    repo: deb [arch=amd64] {{ vscode_repo }} stable main
    state: present
  become: yes

- name: install VS Code Insiders
  apt:
    name: code-insiders
    update_cache: yes
    state: present
  become: yes

- name: Install extensions
  shell: code-insiders --install-extension "{{ item }}"
  with_items: "{{ visual_studio_code_extensions }}"
  become: true
  become_user: "{{ user }}"