---
- name: Remove Firefox Default
  apt:
    name: firefox
    purge: yes
    state: absent
    autoremove: yes
  become: true

- name: Add Mozilla apt repo GPG public key.
  apt_key:
    data: "{{ firefox_ubuntu_ppa_apt_key_content }}"
    state: present
  become: true

- name: Add Mozilla Daily apt repo for Firefox.
  apt_repository:
    repo: "{{ firefox_ubuntu_ppa }}"
    update_cache: yes
    state: present
  become: true
  
- name: Install Firefox.
  apt:
    name: firefox
    state: present
  become: true