---
- name: Add spotify repo
  apt_repository: 
    repo: "{{ spotify_repo }}" 
    update_cache: yes 
    state: present
  become: true

- name: Install Spotify
  apt: 
    name: "spotify-client" 
    state: latest
    force: yes
  become: true