- name: Check if mattermost is installed
  command: dpkg-query -W mattermost-desktop
  register: mattermost_check_deb
  failed_when: mattermost_check_deb.rc > 1
  changed_when: mattermost_check_deb.rc == 1

- name: Download .deb
  get_url: 
    url: "{{ mattermost_url }}"
    dest: "/tmp/mattermost.deb"
  when: mattermost_check_deb.rc == 1

- name: Install latest mattermost package
  apt: 
    deb: "/tmp/mattermost.deb"
    update_cache: yes
  when: mattermost_check_deb.rc == 1
  become: true