---
- name: Remove Java
  apt:
    name: openjdk* 
    purge: yes
    state: absent
    autoremove: yes
  become: true

- name: Add Java repo
  apt_repository: 
    repo: "{{ java_repo }}" 
    update_cache: yes
    state: present
  become: true

- name: Accept License Java 8
  debconf:
    name: "{{ apt_java_package }}"
    question: "shared/accepted-oracle-license-v1-1"
    value: "true"
    vtype: "select"
  become: true

- name: Wait for automatic system updates
  become: true
  shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done;
  
- name: Install Java
  apt:
    name: "{{ apt_java_package }}"
    state: latest
    update_cache: yes
  become: yes

- name: Wait for automatic system updates
  become: true
  shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done;